apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nginx-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: dante.cloudns.ph		
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: nginx-basic
            port:
              number: 80